name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'
      - name: FTP Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: $FTP_SERVER
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
