name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: '2''
      - name: FTP Deploy to server
        run: echo ${{secrets.FTP_SERVER}} ${{env.FTP_SERVER}} ${{vars.FTP_SERVER}}
#        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#        with:
#          server: ${{env.FTP_SERVER}}
#          username: ${{env.FTP_USERNAME}}
#          password: ${{env.FTP_PASSWORD}}
