name: PHP Composer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'
      - name: FTP Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        env:
          FTP_USERNAME: ${{ secrets.GITHUB_TOKEN }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        with:
          server: 'ftp.planiversity.com'
          username: ${{ FTP_USERNAME }}
          password: ${{ FTP_PASSWORD }}
